Repository Kuama-IT/just_audio, pull requests merged in 2022-08, with the labels that each got.

#1 add stop, pitch and fix swift code
  just_audio/example/ios/Podfile.lock
  just_audio/example/ios/Runner.xcodeproj/project.pbxproj
  just_audio/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  just_audio/example/lib/main.dart
  just_audio/ios/Classes/JustAudioPlayer.swift
  just_audio/lib/just_audio.dart
Labels: size/L

#9 Update FUNDING.yml
  .github/FUNDING.yml
Labels: size/XS

#23 Simple script to copy files from darwin folder to macos/ios folder
  .gitignore
  tools/cli/.gitignore
  tools/cli/README.md
  tools/cli/analysis_options.yaml
  tools/cli/lib/sync_darwin_folder.dart
  tools/cli/pubspec.yaml
Labels: size/L, devops
